config/routes.rb
require 'sidekiq/web'

 Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: "questions#index"
  post 'search', action: :search, controller: 'search'
  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :cancel_vote
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: [:voteable, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: [:voteable, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :other, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Attacheable
  include Voteable
  include Commentable

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :badge, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }

  accepts_nested_attributes_for :badge, reject_if: :all_blank

  after_create :create_subscription

  def best_answer
    answers.best_answer.first
  end

  private

  def create_subscription
    Subscription.create(user_id: user_id, question_id: id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: [:show, :destroy, :update]
  authorize_resource

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    question = current_resource_owner.questions.new(question_params)

    if question.save
      render json: question
    else
      render json: question.errors
    end
  end

  def update
    if @question.update(question_params)
      render json: @question
    else
      render json: @question.errors
    end
  end

  def destroy
    @question.destroy
    render json: { message: 'Destroyed succesfully' }
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted
  include Commented

  before_action :find_question, only: [:show, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
    gon.push({currentUser: current_user})
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
    gon.push({currentUser: current_user})
    gon.push({question_id: @question.id})
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_badge
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question succesfully created.'
    else
      render :new
    end
  end

  def update
    binding.pry
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    message = 'Destroyed succesfully'
    redirect_to questions_path, notice: message
  end

  private

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast('questions', {partial: ApplicationController.render( partial: 'questions/question', locals: { question: @question, current_user: nil }),
                                               question: @question})
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url, :done, :_destroy], badge_attributes: [:title, :image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
li class = 'list-group-item'
  div id="question-id-#{question.id}"
    = link_to question.title, question_path(question), style: "font-size: 20px; text-decoration: none"
    - if current_user && current_user.author_of?(question)
      p style = "position:absolute; top:0; right:1%;"
        = link_to octicon("x-circle", class: 'text-danger', height: "25"), question_path(question), method: :delete, remote: true, id: "delete-#{question.id}-question"
      p style = "position:absolute; top:0; right:4%;"
        = link_to octicon("pencil", class: 'text-danger', height: "25"), "#", remote: true, class: "mr-2 edit-question-link",  data: { question_id: question.id }, id: "edit-#{question.id}-question"
      = form_with model: question, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
        div class = 'form-group'
          = f.label :title, 'Your Question title'
          = f.text_field :title, class: "form-control"
          br
          = f.label :body, 'Your Question body'
          = f.text_area :body, class: "form-control"
          br
          = f.label :files
          = f.file_field :files, multiple: true, direct: true
          br
          = f.fields_for :links do |link|
            div class = 'form-group'
              = render 'links/link_fields', f: link
          #new-links
            = link_to_add_association 'Add one more link', f, :links, partial: 'links/link_fields'
          br
          = f.submit 'Save', class: 'btn btn-success'
          = button_to 'Cancel', '#', class: 'btn btn-danger cancel-edit-question-link', data: { question_id: question.id }
    br
    p style = 'font: 10px' class="d-inline text-muted mr-2"
      = "#{question.user.email} #{question.created_at.to_date} #{question.answers.count} answers #{question.comments.count} comments"

app/views/questions/index.html.slim
.question-errors

h2 All questions

- cache collection_cache_key_for :question do
  .questions
    ul class = 'list-group'
      = render @questions

app/views/questions/make_comment.js.erb
$('.question').find('.comment_errors').html("<%= render 'shared/errors', resource: @comment %>");

<% if @comment.persisted? %>
  $('.question_comment_title').text("Comments: <%= @comment.commentable.comments.count %>")
  $('.question_comments').append("<%= j render @comment %>")
<% end %>

app/views/questions/new.html.slim
=render 'shared/errors', resource: @question
div class = 'row justify-content-center mt-5'
  div class = "col col-md-4 border border-dark rounded"
    = form_with model: @question, local: true do |f|
      div class = 'form-group'
        p
          = f.label :title
          = f.text_field :title, class: "form-control"
        p
          = f.label :body
          = f.text_area :body, class: "form-control"
        p
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true

      #new-links
        = f.fields_for :links do |link|
          div class = 'form-group'
            = render 'links/link_fields', f: link
        .links
          = link_to_add_association 'Add one more link', f, :links, partial: 'links/link_fields'
      #new-badge
        = f.fields_for :badge do |b|
          div class = 'form-group'
            p
              = b.label :title, 'Badge title'
              = b.text_field :title, class: "form-control"
            p
              = b.label :image
              = b.file_field :image, direct_upload: true

      p= f.submit 'Ask Question', class: "btn btn-success", style: "margin-left: 30%"

app/views/questions/show.html.slim
- cache @question do
  div class = 'question mt-3'
    div class = 'question_title border-bottom'
      h1 style = "font-size: 30px"
        = @question.title
    div class = 'question_body border-bottom'
      p= @question.body
      - if @question.badge
        p Badge:
        = @question.badge&.title
        = image_tag @question.badge&.image

      - if @question.files.attached?
        h3 style = "font-size: 20px"
          = "Files:"
        .question-files-list
          = render @question.files

      - unless @question.links.empty?
        h3 style = "font-size: 20px"
          = "Links:"
        .question-links-list
          = render @question.links

    div class = "votes_section border-bottom"
      div class = "question_votes_result mb-2"
        h3 style = "font-size: 20px"
          = "Rating result: #{@question.calculate_score}"

      div class = "votes_svg mb-3"
        = link_to octicon("thumbsup", class: 'text-danger', height: "25"), vote_for_question_path(@question), method: :post, remote: true, data: { type: :json }, class: "mr-2", id: "vote_for_question"
        = link_to octicon("thumbsdown", class: 'text-danger', height: "25"), vote_against_question_path(@question), method: :post, remote: true, data: { type: :json }, class: "mr-2", id: "vote_against_question"
        = link_to  octicon("x-circle", class: 'text-danger', height: "25"), cancel_vote_question_path(@question), method: :delete, remote: true, data: { type: :json }, id: "cancel_vote_question"

    .subscribe_block
      - unless current_user&.find_subscription(@question)
        = button_to 'Subscribe', question_subscriptions_path(@question), class: "btn btn-warning subscribe_button", remote: true
      - else
        = button_to 'Unubscribe', subscription_path(current_user&.find_subscription(@question)), class: "btn btn-warning unsunscribe_button", method: :delete, remote: true


    .new_question_comment
      h3 style = "font-size: 20px"
        = 'New Comment'
      .question_comments
        = render 'comments/new_question_comment'
        h3 style = "font-size: 20px" class = "question_comment_title"
            = "Comments: #{@question.comments.count}"
        - unless @question.comments.empty?
          div class = "question-comments"
            ul class = 'list-group'
              = render @question.comments

    div class="new_answer mt-3  border border-dark rounded"
      div class = "m-4"
        h3 style = "font-size: 20px"
          = "New answer:"
        - if signed_in?
          = render 'answers/new'
        - else
          p= 'Please sign in for make an answer'
    div class = "answers question_#{@question.id}_answers mt-3"
      h3 style = "font-size: 20px"
        = "Answers:"
      ul class = 'list-group'
        = render @question.answers.sort_by_best

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.questions').html('<%= j render Question.all %>');
<% end %>