config/routes.rb
require 'sidekiq/web'

 Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: "questions#index"
  post 'search', action: :search, controller: 'search'
  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :cancel_vote
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: [:voteable, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: [:voteable, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :other, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_abilities : user_abilities
    else
      guest_abilities
    end
  end

  def guest_abilities
    can :read, :all
  end

  def admin_abilities
    can :manage, :all
  end

  def user_abilities
    guest_abilities
    can [:create, :make_comment], [Question, Answer]
    can [:vote_for, :vote_against, :cancel_vote], [Question, Answer] do |resource|
      resource.user_id != user.id
    end

    can :create, Subscription
    can :destroy, Subscription,  user_id: user.id
    can :destroy, Link, linkable: { user_id: user.id }
    can [:update, :destroy], [Question, Answer], user_id: user.id
    can :destroy, [Question, Answer], user_id: user.id
    can :mark_as_best, Answer, question: { user_id: user.id }
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Attacheable
  include Voteable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  validates :body, presence: true, length: { minimum: 5 }

  scope :sort_by_best, -> { order(best: :desc)}
  scope :best_answer, -> { where(best: true) }

  after_create :send_notifications

  def mark_as_best
    transaction do
      question.best_answer&.update!(best: false)
      question.badge&.update!(user_id: user_id)
      update!(best: true)
    end
  end

  private

  def send_notifications
    NotificationsJob.perform_later(question)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, presence: true
  validates :uid, presence: true
end

app/models/badge.rb
class Badge < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :title, :image, presence: true
  validate :image_format

  def image_format
    if image.attached?
      errors[:base] << 'Wrong format' if !image.blob.content_type.starts_with?('image/')
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Attacheable

  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: URI::regexp(%w[http https])

  def is_gist?
    URI.parse(url).host.include?('gist')
  end

  def read_gist
    client = Octokit::Client.new
    client.gist(URI.parse(self.url).path.split('/').last).files
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Attacheable
  include Voteable
  include Commentable

  belongs_to :user

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_one :badge, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }

  accepts_nested_attributes_for :badge, reject_if: :all_blank

  after_create :create_subscription

  def best_answer
    answers.best_answer.first
  end

  private

  def create_subscription
    Subscription.create(user_id: user_id, question_id: id)
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :badges
  has_many :subscriptions, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github, :vkontakte]

  def author_of?(resource)
    id == resource.user_id
  end

  def find_subscription(question)
    subscriptions&.find_by(question_id: question.id)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voteable, polymorphic: true
  belongs_to :user
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :find_link, only: %i[destroy]
  authorize_resource

  def destroy
    @link.destroy
  end

  private

  def find_link
    @link = Link.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body>
    <% unless current_page?(new_user_registration_path) || current_page?(new_user_session_path) %>
      <%= render 'shared/navbar' %>
    <% end %>
    <div class = 'flash' >
      <%= render 'shared/flash' %>
    </div>
    <div class = 'container' >
          <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_flash.html.slim
- flash.each do |key, message|
  - if key == 'alert'
    = content_tag :div, message, class: "alert alert-danger", style:"text-align: center;"
  - else
    = content_tag :div, message, class: "alert alert-success", style:"text-align: center;"

app/views/shared/_navbar.html.slim
nav class="navbar navbar-dark" style="background-color: #4F5A6E;"
  = link_to 'Q&A', root_path, class: 'navbar-brand'
  -  if user_signed_in?
    = form_with url: search_path, local: true, class: 'form-inline' do |f|
      = f.text_field :body, class: 'form-control'
      = f.submit 'Find', class: 'btn btn-success'
      = f.select :type, SearchService::TYPES

  ul class="list-inline navbar-nav ml-auto"
    div class="d-flex flex-row"
      li class="nav-item mr-3"
        = link_to 'Add question', new_question_path, class: 'btn btn-success'
      -  if user_signed_in?
        li class="nav-item mr-2"
          = link_to 'My Badges', badges_path, class: 'nav-link'
        li class="nav-item mr-3"
          = link_to 'Log Out', destroy_user_session_path, method: :delete, class: 'nav-link'
      - else
        li class="nav-item mr-2"
          = link_to 'Log In', new_user_session_path, class: 'nav-link'