config/routes.rb
require 'sidekiq/web'

 Rails.application.routes.draw do
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks', confirmations: 'confirmations' }
  root to: "questions#index"
  post 'search', action: :search, controller: 'search'
  concern :voteable do
    member do
      post :vote_for
      post :vote_against
      delete :cancel_vote
    end
  end

  concern :commented do
    member do
      post :make_comment
    end
  end

  resources :questions, concerns: [:voteable, :commented] do
    resources :subscriptions, only: [:create, :destroy], shallow: true
    resources :answers, concerns: [:voteable, :commented], shallow: true do
      member do
        post :mark_as_best
      end
    end
  end

  resources :attachments, only: :destroy
  resources :links, only: :destroy
  resources :badges, only: :index

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        get :me, on: :collection
        get :other, on: :collection
      end

      resources :questions do
        resources :answers, shallow: true
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Attacheable
  include Voteable
  include Commentable

  belongs_to :user
  belongs_to :question, touch: true

  validates :body, presence: true, length: { minimum: 5 }

  scope :sort_by_best, -> { order(best: :desc)}
  scope :best_answer, -> { where(best: true) }

  after_create :send_notifications

  def mark_as_best
    transaction do
      question.best_answer&.update!(best: false)
      question.badge&.update!(user_id: user_id)
      update!(best: true)
    end
  end

  private

  def send_notifications
    NotificationsJob.perform_later(question)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted
  include Commented

  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: %i[create]
  before_action :find_answer, only: %i[destroy update mark_as_best]
  after_action  :publish_answer, only: %i[create]

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params.merge(user: current_user))
  end

  def update
    @answer.update(answer_params)
  end

  def destroy
    @answer.destroy
    flash[:notice] = 'Destroyed successfully'
  end

  def mark_as_best
    @question = @answer.question

    @answer.mark_as_best if current_user.author_of? @question
  end

  private

  def publish_answer
    return if @answer.errors.any?
    ActionCable.server.broadcast("answers_#{params[:question_id]}", {partial: ApplicationController.render( partial: 'answers/answer', locals: { answer: @answer, current_user: nil }),
                                            answer: @answer,
                                            question: @answer.question})
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i[index create]
  before_action :find_answer, only: %i[show update destroy]
  authorize_resource

  def index
    render json: @question.answers, each_serializer: AnswersSerializer
  end

  def show
    render json: @answer, each_serializer: AnswerSerializer
  end

  def create
    answer = @question.answers.new(answer_params.merge(user: current_resource_owner))

    if answer.save
      render json: answer
    else
      render json: answer.errors
    end
  end

  def update
    if @answer.update(answer_params)
      render json: @answer
    else
      render json: @answer.errors
    end
  end

  def destroy
    @answer.destroy
    render json: { message: 'Destroyed succesfully' }
  end

  private
  def answer_params
    params.require(:answer).permit(:body, links_attributes: [:name, :url])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  li class = 'list-group-item'
    .div class = "answer-#{answer.id}-errors"
    - if answer.best
      div class = 'best_answer'
        h3= 'BEST'
        = render 'answers/answer_block', answer: answer, current_user: current_user
        br
    -else
      = render 'answers/answer_block', answer: answer, current_user: current_user

app/views/answers/_answer_block.html.slim
div id = "answer-id-#{answer.id} m-4"
  - if answer.persisted?
      div class = 'answer_body border-bottom'
        p= answer.body
        .answer-files-list
          - unless answer.files.empty?
            p Files:
            = render answer.files, current_user: current_user

        .answer-links-list
          - unless answer.links.empty?
            p Links:
            = render answer.links, current_user: current_user

      div class = "answer_votes_section border-bottom"
        div class = "answer_#{answer.id}_votes_result mb-2"
          h3 style = "font-size: 20px"
            = "Rating result: #{answer.calculate_score}"

        div class = "votes_svg mb-3"
          = link_to octicon("thumbsup", class: 'text-danger', height: "25"), vote_for_answer_path(answer), method: :post, remote: true, data: { type: :json }, class: "mr-2", id: "vote_for_#{answer.id}_answer"
          = link_to octicon("thumbsdown", class: 'text-danger', height: "25"), vote_against_answer_path(answer), method: :post, remote: true, data: { type: :json }, class: "mr-2", id: "vote_against_#{answer.id}_answer"
          = link_to  octicon("x-circle", class: 'text-danger', height: "25"), cancel_vote_answer_path(answer), method: :delete, remote: true, data: { type: :json }, id: "cancel_vote_#{answer.id}_answer"

      div class = "answer_#{answer.id}_comments border-bottom"
        h3 style = "font-size: 20px"
          = 'New Comment'
        .answer_comments
        = render 'comments/new_answer_comment', answer: answer
        h3 style = "font-size: 20px"
            = 'Comments:'
        - unless answer.comments.empty?
          ul class = 'list-group'
            = render answer.comments

      br
      div class = 'btn-group answer_actions'
        - if current_user&.author_of?(answer.question)
          = link_to 'Mark as best', mark_as_best_answer_path(answer), remote: true, method: :post, class: "btn btn-primary"
        -if current_user&.author_of?(answer)
          = link_to 'Edit', '#', class: "edit-answer-link btn btn-warning", data: { answer_id: answer.id }, id: "edit-#{answer.id}-answer"
          = button_to  'Delete', answer_path(answer), method: :delete, remote: true, class: "btn btn-danger"
      div class = "edit_answer_#{answer.id}"
        = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
                div class = 'form-group'
                  p
                    = f.label :body, 'Your answer'
                    = f.text_area :body, class: "form-control"
                  p
                    = f.label :files
                    = f.file_field :files, multiple: true, direct_upload: true
                  p
                  #new-links
                    = link_to_add_association 'Add one more link', f, :links, partial: 'links/link_fields'
                  p
                  = f.submit 'Save', class: "btn btn-success"
                  = button_to 'Cancel', '#', class: 'btn btn-danger cancel-edit-answer-link', data: { question_id: answer.id }
  br

app/views/answers/_new.html.slim
.answer-errors

= form_with model: [@question, @answer] do |f|
  div class = 'form-group'
    p
     = f.label :body
     = f.text_area :body, class: "form-control"
    p
     = f.label :files
     = f.file_field :files, multiple: true, direct_upload: true
    p Links:

    #new-links
      = f.fields_for :links do |link|
        = render 'links/link_fields', f: link
      .links
        = link_to_add_association 'Add one more link', f, :links, partial: 'links/link_fields'

    p
      = f.submit 'Make Answer', class: "btn btn-success"

app/views/answers/create.js.erb
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");
<% if @answer.persisted? %>
  $('.answers').append("<%= j render @answer %>")
  $('#answer_body').val('')
<% end %>

app/views/answers/destroy.js.erb
$('.flash').html("<%= j render 'shared/flash' %>");
$('.answers').html('<%= j render @answer.question.answers %>');

app/views/answers/make_comment.js.erb
var node = $(".answer_" + <%= @comment.commentable.id %>  + "_comments");
node.children(".comment_errors").html("<%= render 'shared/errors', resource: @comment %>");
<% if @comment.persisted? %>
  node.append("<%= j render @comment %>")
<% end %>

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render @question.answers.sort_by_best %>');

app/views/answers/show.html.slim
= @answer.body

app/views/answers/update.js.erb
$('.answer-<%= @answer.id %>-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @answer.question.answers %>');
<% end %>